language: node_js
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
env:
  global:
    # github
    - secure: "v7bpSf2rmj7kh/K8YajkMuxOUUel6L9qJqzgekwV0ZplRO3cmni7mCBCwmMhdSRzuC1dXu6uTIE0cAOclvk6dyRMRe/5L+vmciAbk+yTMq1w1fvi3MFBkU3H8yKtYID3/nRNTmH8W4B5PryfCuN73umVKkQEsxK0D8huWZZ2Fp5g3LrhN2j53sI2GYvUffVQErPwGM3czniu5t62vO4EwjPJQ/wcV6nLL5JYCc5cIO8y6+ETbo6kRzUV8qDR0PyVpskVuZaamAoFD0IrSFaw/KA2yq2w3okD9Gcm+/u5NpBEKywHucNaRRqEsu1fp/mPq2ANK19csT4GDEjlJgSDnXjkM+iAKEnx6+ySNNcKNbH0LMH7LIvSysJ2oZbgYYtKU3EePR32uW1kTPQs7bZ2I06H5LgPvPL3TTTCC/WVAH0RaS1RHXMuS/jau37pvoMWRVxNi3k5fS1PDraGftl45WcpiZPN7F27AFBpJxHuRhdOFehpZE13D46HTVUlQySARFSB/LS20heiIrF2qXA/ptVt1vAhSew74bjElWypkpIGcwaO8Vxu1FldPhvsqo5ZCYxa62JrPGGERnfYgmgIsMEyXZWCShSrjMesA4BsSx15fGOZV4T2UA/DYKQ/zCyoknDf0HaQUxUW5Pk5fHYyBlZ1pw+5kZhyzwaxfpJTcbo="
    # npm
    - secure: "td1osfqObT84K4+GTB087T22djNwEkTI91nu6XMXqUZyxfT2asYbLqQXWadVWfYSMhuJTfu54Udqj635AJUeOlgPS7GOrL7Z2zPHORoY1RWFbjXJf33hTNCi1wLFDUHXSW/vyBjINymHq2oS//bLrGTDsLzHfC5BvaaimaJosa81WQfSEacdOs7LmcF9JiI3CNiUSYauyiatIFAbUglyBqsSoyhIAe+efYpxQmMtHUjbwr9t/7mfyOYPdrkTOdysilO1/6tFvWquGmbrf/vp/NTwGKlk/4Wfv/62zra/KB9gx/ETP1aYRayNkbnzIrjVmdIZXhJw1LbKuOjI8NnvpI4suK6BMrW7zeC0H+x+/In+fBj8iRQqcfQqr8ohld01Z96EB8T+gk/0gvERh8aUBYfvqxjVuRZ39C5zzyNmTHV95ywvnW7Ag9P4X1OYZQ1F5GRi/+h2xYQzkqzRd4PDjMHXk9uJ/P0NQAxI211QlkZBzDS93kZU/nQTcqWQHdGjYzmMIAjghkHMir8qLwe5Exn2P1KyjPbCSPjD7/NEZYitsh8oOvnHkn7tQewdzrwjxlxtoIKrRnalgXU38Guav+2nK+g2YPH5bhMtZ05o2LS86yxGFTdGhWdn3r9xBt5c7Aqf2GtzrWlomtmX1Pqko7XTnYwQ8ZTkS/8ZlP4kJds="
cache:
  npm: true
  directories:
    - dist
    - reports
jobs:
  include:
    - stage: prepare cache
      name: install
      before_install:
        - rm -rf dist reports
      install:
        - npm i
    - stage: website
      name: build
      script:
        # - echo $TRAVIS_PULL_REQUEST_BRANCH
        # - echo $TRAVIS_BRANCH
        # - echo $TRAVIS_COMMIT
        # - echo $TRAVIS_PULL_REQUEST_SHA
        - if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then export PT_BRANCH=$TRAVIS_BRANCH; else export PT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; fi
        - if [ -z "$TRAVIS_PULL_REQUEST_SHA" ]; then export PT_COMMIT=$TRAVIS_COMMIT; else export PT_COMMIT=$TRAVIS_PULL_REQUEST_SHA; fi
        # - echo $PT_COMMIT
        # - echo $PT_BRANCH
        - npm run build --base=/nuxt-custom-elements/
    - stage: deploy
      if: branch = master
      install:
        - npm i semantic-release @semantic-release/exec @semantic-release/git @semantic-release/changelog --no-save
      script:
        - npx semantic-release --provider=github
        - mkdir gh-pages gh-pages/reports
        - cp -R dist/nuxt-custom-elements/* gh-pages/
        - cp -R reports/* gh-pages/reports/
        - touch gh-pages/.nojekyll
      deploy:
        provider: pages
        cleanup: false
        github_token: $GITHUB_TOKEN
        local_dir: gh-pages/
        on:
          branch: master
        edge: true
